### ISSUE TITLE
SDK Question. 

### ISSUE THREAD

**Issue by john-delivuk** [mhausenblas/reshifter#23]
This is more of an inquiry. Why use the minio for s3 over the aws sdk? You get bound to using AWS Access keys over being able to leverage IAM profiles as well. Would you be open to a PR swapping out sdk for something more robust?

**Comment by mhausenblas** [comment]
Thanks for your interest @john-delivuk. Not sure I'm following. AFAICT, there seem to be two orthogonal things going on here: 1. being able to leverage IAM profiles, and 2. you suggesting that Minio is not "robust". Ad 1. I'd say that the current setup allows for most portability (since IAM is only available in AWS) so to me that's not a compelling reason to move away from Minio. Ad 2., I'm not sure what you mean with "something more robust", can you maybe give an example?

**Comment by john-delivuk** [comment]
I can see how using minio provides a smaller foot print and sufficient for uploading an object. Using the aws-sdk would allow you to use all compatible forms of authentication, this allowing for the most versatile deployments in aws , as well as maintaining the same outside of. Seeing as minio does have some versatility because you can use generic s3 compatible object stores vs official s3, there is a benefit there, but I'm _fairly_ confident this can be achieved using the official sdk as well. The features will be basically be the same, that was poor phrasing on my part. This comes down to management and offering multiple options to the user.
